//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NfoMetadata.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NfoMetadata.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable or disable Nfo metadata files, edit a library in Emby library setup and locate the metadata savers section. Changes to metadata settings will only apply to new content added to your library. To apply the changes to existing titles, you&apos;ll need to refresh their metadata manually..
        /// </summary>
        public static string HeaderKodiMetadataHelp {
            get {
                return ResourceManager.GetString("HeaderKodiMetadataHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date format:.
        /// </summary>
        public static string LabelKodiMetadataDateFormat {
            get {
                return ResourceManager.GetString("LabelKodiMetadataDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All dates within nfo&apos;s will be read and written to using this format..
        /// </summary>
        public static string LabelKodiMetadataDateFormatHelp {
            get {
                return ResourceManager.GetString("LabelKodiMetadataDateFormatHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy extrafanart into extrathumbs.
        /// </summary>
        public static string LabelKodiMetadataEnableExtraThumbs {
            get {
                return ResourceManager.GetString("LabelKodiMetadataEnableExtraThumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When downloading images they can be saved into both extrafanart and extrathumbs if needed. This is only recommended if you have other software that requires this..
        /// </summary>
        public static string LabelKodiMetadataEnableExtraThumbsHelp {
            get {
                return ResourceManager.GetString("LabelKodiMetadataEnableExtraThumbsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable path substitution.
        /// </summary>
        public static string LabelKodiMetadataEnablePathSubstitution {
            get {
                return ResourceManager.GetString("LabelKodiMetadataEnablePathSubstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables path substitution of image paths using the server&apos;s path substitution settings..
        /// </summary>
        public static string LabelKodiMetadataEnablePathSubstitutionHelp {
            get {
                return ResourceManager.GetString("LabelKodiMetadataEnablePathSubstitutionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save image paths within nfo files.
        /// </summary>
        public static string LabelKodiMetadataSaveImagePaths {
            get {
                return ResourceManager.GetString("LabelKodiMetadataSaveImagePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is only recommended if you have other software using the nfo files that requires this..
        /// </summary>
        public static string LabelKodiMetadataSaveImagePathsHelp {
            get {
                return ResourceManager.GetString("LabelKodiMetadataSaveImagePathsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save user watch data to nfo&apos;s for:.
        /// </summary>
        public static string LabelKodiMetadataUser {
            get {
                return ResourceManager.GetString("LabelKodiMetadataUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable this to save watch data to Nfo files for other applications to utilize..
        /// </summary>
        public static string LabelKodiMetadataUserHelp {
            get {
                return ResourceManager.GetString("LabelKodiMetadataUserHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My description.
        /// </summary>
        public static string MyDescription {
            get {
                return ResourceManager.GetString("MyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to egerg.
        /// </summary>
        public static string NfoMetadataOptions_UserId_egerg {
            get {
                return ResourceManager.GetString("NfoMetadataOptions_UserId_egerg", resourceCulture);
            }
        }
    }
}
